### ISSUE TITLE
Persistence Epic

### ISSUE THREAD

**Issue by gotjoshua** [onezoomin/PomodoroLogger#1]
- [ ] abstract a persist fx that can write to 
   - [ ] indexDB via Dexie
   - [ ] [GitLab via graphQL](https://docs.gitlab.com/ee/api/graphql/sample_issue_boards.html)
   - [ ] neDB for backwards compatibility
